# Entorno de Desarrollo Docker
# Autor: nunezlagos
# Archivo compose principal que referencia la configuración organizada

version: '3.8'

# Este archivo sirve como punto de entrada conveniente
# Toda la configuración real está en config/stack-compose.yml

# Para usar este entorno:
# docker-compose up -d

# Para Traefik (proxy reverso):
# docker-compose -f config/traefik-compose.yml up -d

# Para el stack completo:
# docker-compose -f config/stack-compose.yml up -d

# O usar los scripts proporcionados:
# ./scripts/up.sh

services:
  # Este archivo incluye la configuración del stack principal
  # Ejecutar: docker-compose -f config/stack-compose.yml up -d
  
  # Por conveniencia, también puedes ejecutar:
  # docker-compose up -d
  # Esto iniciará los servicios definidos en config/stack-compose.yml
  
include:
  - config/stack-compose.yml